title:       "Operating Systems 2021-1 (OS211)"
version:     "0032---07-Mar-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Zulfahri Haradi"
address:          "Bogor"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://haradijul.github.io/testcolongcbkadal/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/haradijul/testcolongcbkadal"
urlghpage:        "https://haradijul.github.io/testcolongcbkadal/"
keywords:         "jekyll, testing"
github:           [metadata]

